CREATE TABLE land_types (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(10) NOT NULL UNIQUE,
    color CHAR(7) NOT NULL
);

INSERT INTO land_types (name, code, color) VALUES
('Đất nông nghiệp', 'NNP', '#ffff64'),
('Đất sản xuất nông nghiệp', 'SXN', '#fffc6e'),
('Đất trồng cây hàng năm', 'CHN', '#fffc78'),
('Đất trồng lúa', 'LUA', '#fffc82'),
('Đất chuyên trồng lúa nước', 'LUC', '#fffc8c'),
('Đất trồng lúa nước còn lại', 'LUK', '#fffc96'),
('Đất trồng lúa nương', 'LUN', '#fffcb4'),
('Đất trồng cây hàng năm khác', 'HNK', '#fff0b4'),
('Đất bằng trồng cây hàng năm khác', 'BHK', '#fff0b4'),
('Đất nương rẫy trồng cây hàng năm khác', 'NHK', '#fff0b4'),
('Đất trồng cây lâu năm', 'CLN', '#ffd2a0'),
('Đất lâm nghiệp', 'LNP', '#aaff32'),
('Đất nuôi trồng thủy sản', 'NTS', '#aaffff'),
('Đất làm muối', 'LMU', '#fffffe'),
('Đất nông nghiệp khác', 'NKH', '#f5ffb4'),
('Đất phi nông nghiệp', 'PNN', '#ffff64'),
('Đất ở', 'OTC', '#ffb4ff'),
('Đất ở tại nông thôn', 'ONT', '#ffd0ff'),
('Đất ở tại đô thị', 'ODT', '#ffa0ff'),
('Đất chuyên dùng', 'CDG', '#ffa0aa'),
('Đất xây dựng trụ sở cơ quan', 'TSC', '#ffaaa0'),
('Đất quốc phòng', 'CQP', '#ff6450'),
('Đất an ninh', 'CAN', '#ff5046'),
('Đất xây dựng công trình sự nghiệp', 'DSN', '#ffa0aa'),
('Đất xây dựng trụ sở của tổ chức sự nghiệp', 'DTS', '#faaaa0'),
('Đất xây dựng cơ sở văn hóa', 'DVH', '#ffaaa0'),
('Đất xây dựng cơ sở dịch vụ xã hội', 'DXH', '#ffaaa0'),
('Đất xây dựng cơ sở y tế', 'DYT', '#ffaaa0'),
('Đất xây dựng cơ sở giáo dục và đào tạo', 'DGD', '#ffaaa0'),
('Đất xây dựng cơ sở thể dục thể thao', 'DTT', '#ffaaa0'),
('Đất xây dựng cơ sở khoa học và công nghệ', 'DKH', '#ffaaa0'),
('Đất xây dựng cơ sở ngoại giao', 'DNG', '#ffaaa0'),
('Đất xây dựng công trình sự nghiệp khác', 'DSK', '#ffaaa0'),
('Đất sản xuất, kinh doanh phi nông nghiệp', 'CSK', '#ffa0aa'),
('Đất khu công nghiệp', 'SKK', '#faaaa0'),
('Đất cụm công nghiệp', 'SKN', '#faaaa0'),
('Đất khu chế xuất', 'SKT', '#faaaa0'),
('Đất thương mại, dịch vụ', 'TMD', '#faaaa0'),
('Đất cơ sở sản xuất phi nông nghiệp', 'SKC', '#faaaa0'),
('Đất sử dụng cho hoạt động khoáng sản', 'SKS', '#cdaacd'),
('Đất sản xuất vật liệu xây dựng, làm đồ gốm', 'SKX', '#cdaacd'),
('Đất có mục đích công cộng', 'CCC', '#ffaaa0'),
('Đất giao thông', 'DGT', '#ffaa32'),
('Đất thủy lợi', 'DTL', '#aaffff'),
('Đất có di tích lịch sử - văn hóa', 'DDT', '#ffaaa0'),
('Đất danh lam thắng cảnh', 'DDL', '#ffaaa0'),
('Đất sinh hoạt cộng đồng', 'DSH', '#ffaaa0'),
('Đất khu vui chơi, giải trí công cộng', 'DKV', '#ffaaa0'),
('Đất công trình năng lượng', 'DNL', '#ffaaa0'),
('Đất công trình bưu chính viễn thông', 'DBV', '#ffaaa0'),
('Đất chợ', 'DCH', '#ffaaa0'),
('Đất bãi thải, xử lý chất thải', 'DRA', '#cdaacd'),
('Đất công trình công cộng khác', 'DCK', '#ffaaa0'),
('Đất cơ sở tôn giáo', 'TON', '#ffaaa0'),
('Đất cơ sở tín ngưỡng', 'TIN', '#ffaaa0'),
('Đất nghĩa trang, nghĩa địa, nhà tang lễ, nhà hỏa táng', 'NTD', '#d2d2d2'),
('Đất sông, ngòi, kênh, rạch, suối', 'SON', '#a0ffff'),
('Đất có mặt nước chuyên dùng', 'MNC', '#b4ffff'),
('Đất phi nông nghiệp khác', 'PNK', '#ffaaa0'),
('Đất chưa sử dụng', 'CSD', '#fffffe'),
('Đất có mặt nước ven biển (chỉ tiêu quan sát)', 'MVB', '#b4ffff');
